
version: '3'

services:
  # Database
  db1:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: wordpress1
      MYSQL_PASSWORD: wordpress1
    
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db1
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9099:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

  # Wordpress
  wordpress:
    depends_on:
      - db1
    image: wordpress:latest
    ports:
      - '8088:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: wordpress
   
      
  wpsite:
volumes:
  db_data:
